# Generated by Django 2.1.7 on 2019-03-18 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('plate', models.CharField(max_length=255)),
                ('onboard', models.DateTimeField()),
                ('valid', models.BooleanField()),
            ],
            options={
                'verbose_name': '公交',
                'verbose_name_plural': '公交',
            },
        ),
        migrations.CreateModel(
            name='Bus2Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schduel_type', models.IntegerField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BusApp.Bus')),
            ],
            options={
                'verbose_name': '公交 - 线路',
                'verbose_name_plural': '公交 - 线路',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('charger', models.CharField(blank=True, max_length=30)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('superior', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='BusApp.Department')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('bus_count', models.IntegerField()),
                ('line_length', models.IntegerField()),
                ('earliest_depart_time', models.TimeField()),
                ('latest_arrive_time', models.TimeField()),
                ('buses', models.ManyToManyField(related_name='buses', through='BusApp.Bus2Line', to='BusApp.Bus')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BusApp.Department')),
            ],
            options={
                'verbose_name': '线路',
                'verbose_name_plural': '线路',
            },
        ),
        migrations.CreateModel(
            name='Line2Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_order', models.IntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BusApp.Line')),
            ],
            options={
                'verbose_name': '线路-站点',
                'verbose_name_plural': '线路-站点',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=30)),
                ('valid', models.BooleanField()),
                ('sim', models.CharField(max_length=30)),
                ('entrancen_lon', models.FloatField()),
                ('entrance_lat', models.FloatField()),
                ('entrancen_dir', models.FloatField()),
                ('exit_lon', models.FloatField()),
                ('exit_lat', models.FloatField()),
                ('exit_dir', models.FloatField()),
                ('distance', models.IntegerField()),
                ('lines', models.ManyToManyField(related_name='site_lines', through='BusApp.Line2Site', to='BusApp.Line')),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点',
            },
        ),
        migrations.AddField(
            model_name='line2site',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BusApp.Site'),
        ),
        migrations.AddField(
            model_name='line',
            name='sites',
            field=models.ManyToManyField(related_name='sites', through='BusApp.Line2Site', to='BusApp.Site'),
        ),
        migrations.AddField(
            model_name='bus2line',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BusApp.Line'),
        ),
        migrations.AddField(
            model_name='bus',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BusApp.Department'),
        ),
        migrations.AddField(
            model_name='bus',
            name='lines',
            field=models.ManyToManyField(related_name='bus_lines', through='BusApp.Bus2Line', to='BusApp.Line'),
        ),
    ]
