# Generated by Django 2.1.7 on 2019-03-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='lines',
        ),
        migrations.AddField(
            model_name='site',
            name='lines',
            field=models.ManyToManyField(related_name='lines', through='BusApp.Line2Site', to='BusApp.Line'),
        ),
    ]
