# Generated by Django 2.1.7 on 2019-03-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusApp', '0002_auto_20190308_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='lines',
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_lines',
            field=models.ManyToManyField(related_name='lines', through='BusApp.Bus2Line', to='BusApp.Line'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_lines',
            field=models.ManyToManyField(related_name='site_lines', through='BusApp.Line2Site', to='BusApp.Line'),
        ),
    ]
