# Generated by Django 2.1.7 on 2019-03-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusApp', '0003_auto_20190308_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='site_lines',
            new_name='lines',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='bus_lines',
        ),
        migrations.AddField(
            model_name='bus',
            name='lines',
            field=models.ManyToManyField(related_name='bus_lines', through='BusApp.Bus2Line', to='BusApp.Line'),
        ),
    ]
